import time
import json
import re
from openai import OpenAI
import os


OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    raise RuntimeError("Missing OPENAI_API_KEY in environment variables")


client = OpenAI(api_key=OPENAI_API_KEY)


def send_image(prompt, pdf_file, page_number, image_base64):
    image_data_url = f"data:image/png;base64,{image_base64}"
    json_instruction = (
        "\n\nRespond only in valid JSON format. "
    )

    prompt_with_context = (
        f"{prompt}\n\nFile: {pdf_file}, Page: {page_number}.{json_instruction}"
    )

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt_with_context},
                    {"type": "image_url", "image_url": {"url": image_data_url}}
                ]
            }],
            max_tokens=1024
        )
        text = response.choices[0].message.content

        json_data = extract_json(text)

        if json_data:
            print(f"Received JSON (Page {page_number})")
            print(f"Raw LLM response (Page {page_number}):\n{text}\n")
            print(f"Parsed JSON (Page {page_number}):\n{json.dumps(json_data, indent=2)}\n")
            return {
                "pdf_file": pdf_file,
                "page_number": page_number,
                "json_data": json_data
            }
        else:
            print(f"The model did not return valid JSON:\n{text}")
            return None

    except Exception as e:
        print(f"Error in {pdf_file} Page {page_number}: {e}")
        return None
    finally:
        time.sleep(2)


def extract_json(text):
    """
    Tries to extract valid JSON from text generated by an LLM.
    """
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                return None
        return None
